services:
  server:
    build: .
    env_file: .env
    stop_signal: SIGINT
    restart: always
    ports:
      - 2456-2457:2456-2457/udp
    volumes:
      - ./config/valheim_plus.cfg:/valheim/BepInEx/config/valheim_plus.cfg
      - ./data:/root/.config/unity3d/IronGate/Valheim
